### ISSUE TITLE
使用自己的数据

### ISSUE THREAD

**Issue by cap2hb** [biubiubiu01/EchartsMap#7]
你好！后台是php的，请问如何通过ajax方式访问自己的数据？

**Comment by biubiubiu01** [comment]
> 你好！后台是php的，请问如何通过ajax方式访问自己的数据？

你就正常调用$.get或$.post拿到数据，之后就和vue的一样，只要能拿到数据，把数据变成指定的格式即可。

**Comment by cap2hb** [comment]
> > 你好！后台是php的，请问如何通过ajax方式访问自己的数据？
> 
> 你就正常调用$ .get或$ .post拿到数据，之后就和vue的一样，只要能拿到数据，把数据变成指定的格式即可。

好的，多谢！
